alphabet = 'the quick red fox jumps over the lazy brown dog'.split()
all_letters = ''.join(alphabet)
unique_letters = set(all_letters)
indx = alphabet.index('fox')
test_delim = '~'.join(alphabet)

print(alphabet)
print(all_letters)
print(len(unique_letters))
print(sorted(unique_letters))
print(indx)
print(test_delim)
